### PR TITLE
feat: Add image urls to metadata

### PR DESCRIPTION
**Pull request by andremacola**
Sometimes an image is not included in text body and we can extract by some SEO TAGS

Issue: https://github.com/adbar/trafilatura/issues/281

Unfortunately I didn't have time to create the tests

### CODE REVIEW

**Comment by adbar** [comment]
Hi @andremacola, that's basically the idea, thanks for the draft!
You still have to adapt the tests to the new metadata though, and please also add tests for the new lines of code.

**Comment by andremacola** [comment]
> Hi @andremacola, that's basically the idea, thanks for the draft! You still have to adapt the tests to the new metadata though, and please also add tests for the new lines of code.

Nice. For now this is working for my use case. I'll try to update the tests by the end of the next week.

**Comment by adbar** [comment]
@andremacola could you please update the tests?

**Comment by adbar** [comment]
@boxabirds, thanks, we'll have a look

**Comment by andremacola** [comment]
hey @adbar Sorry for late response. I am very busy at work until next week. I'll try my best to update the tests when I'm free

**Comment by andremacola** [comment]
Created image tests. Just trying to fix `test_txttocsv` unit_test

**Comment by adbar** [comment]
Hi @andremacola, thanks for completing the PR and making the tests pass!

Before I review your additions, do you want to have a look at the expressions mentioned by @boxabirds above? I'm not primarily interested in images but I guess it would be interesting to add more ways to extract the relevant data?

**Comment by andremacola** [comment]
@adbar  I'm already pulling from OG, Twitter and images meta tags.

Using extruct for extract all metadata it's easier but maybe there will be performance hit.

Maybe in a next step I can check inside the json-ld format not only for images but also for other parameters.

But as I said, that's for a next version. I've been pretty busy lately unfortunately.

**Comment by boxabirds** [comment]
It’s really great what you already added — thanks!

**Comment by adbar** [comment]
Nice, I'll review and integrate the PR by next week at the latest.

**Pull request merged**
