### PR TITLE
Performance enhancement

### PR DESCRIPTION
**Pull request by deedy5**
### I. Test file
<details>
  <summary>test2.py</summary>

```python3
from time import time

import requests
from trafilatura import extract


if __name__ == '__main__':
    urls = ["https://en.wikipedia.org/wiki/List_of_Hindi_songs_recorded_by_Asha_Bhosle",
            "https://en.wikipedia.org/wiki/2022_in_video_games",
            "https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Kuwait",
            "https://en.wikipedia.org/wiki/Presidency_of_Rodrigo_Duterte",
            "https://en.wikipedia.org/wiki/List_of_2021%E2%80%9322_NBA_season_transactions",
            "https://en.wikipedia.org/wiki/2022_in_sports",
            "https://en.wikipedia.org/wiki/Firefox_version_history",
            "https://en.wikipedia.org/wiki/List_of_common_misconceptions",
            "https://en.wikipedia.org/wiki/Same-sex_union_legislation",
            "https://en.wikipedia.org/wiki/Presidency_of_Donald_Trump",]

    cum_time = 0
    for url in urls:        
        resp = requests.get(url)
        t0 = time()
        result = extract(resp.text)
        cum_time = cum_time + time() - t0
    print(cum_time)
```
</details>

### II. Test [pprofile](https://pypi.org/project/pprofile/)
```python3
kernprof -lv test2.py
```
before
```python3
Total time: 0.544693 s
File: /trafilatura-master/trafilatura/utils.py
Function: remove_control_characters at line 221

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   221                                           @profile
   222                                           def remove_control_characters(string):
   223                                               '''Prevent non-printable and XML invalid character errors'''
   224     25998     544693.0     21.0    100.0      return ''.join([c for c in string if c.isprintable() or c.isspace()])
```

after
```python3
Total time: 0.169241 s
File: /trafilatura-master/trafilatura/utils.py
Function: remove_control_characters at line 227

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   227                                           @profile
   228                                           def remove_control_characters(string):
   229                                               '''Prevent non-printable and XML invalid character errors'''
   230     25998     169241.0      6.5    100.0      return ''.join(filter(is_printable_or_space, string))
```
### III. Test [vprof](https://pypi.org/project/vprof/)
```python3
vprof -c -h test2.py
```
before
before

after
after

### CODE REVIEW

**Comment by adbar** [comment]
Hi @deedy5, thanks for the PR.

I believe the results you get are only due to function caching. I see no improvement by running the following test, your solution without cache is about 50% slower:

```
def is_printable_or_space(character):
    return character.isprintable() or character.isspace()


if __name__ == '__main__':
    import timeit
    print(timeit.timeit('"".join([c for c in string if c.isprintable() or c.isspace()])', setup='string = "abcde fghij"'))
    print(timeit.timeit('"".join(filter(is_printable_or_space, string))', setup='from __main__ import is_printable_or_space; string = "abcde fghij"'))
```

Do you confirm?

**Comment by deedy5** [comment]
The average string length at the input of the function is counted in tens of characters. 
Here is the column with the string length from the previous test.
[test.xlsx](https://github.com/adbar/trafilatura/files/9454548/test.xlsx)

### I. timeit

Here are the tests with string lengths from 10 to 100.

<details>
<summary>test.py</summary>

```python3
from functools import lru_cache
from random import randint


def is_printable_or_space(character):
    return character.isprintable() or character.isspace()

@lru_cache(maxsize=1114111)
def is_printable_or_space2(character):
    return character.isprintable() or character.isspace()


if __name__ == '__main__':
    import timeit

    for str_length in range(10, 100, 10):
        print(f"\n\n{str_length=}")
        string_input = ''.join(chr(randint(97, 122)) for _ in range(str_length))
        print(f"{string_input = }")                               
        
        print("Default", end=" : ")
        print(timeit.timeit('"".join([c for c in string if c.isprintable() or c.isspace()])', setup=f'string = "{string_input}"'))

        # no cache
        print("list_comprehension", end=" : ")
        print(timeit.timeit('"".join([c for c in string if is_printable_or_space(c)])', setup=f'from __main__ import is_printable_or_space; string = "{string_input}"'))
        print("filter", end=" : ")
        print(timeit.timeit('"".join(filter(is_printable_or_space, string))', setup='from __main__ import is_printable_or_space; string = "{string_input}"'))

        # cache
        print("list_comprehension + lru_cache", end=" : ")
        print(timeit.timeit('"".join([c for c in string if is_printable_or_space2(c)])', setup='from __main__ import is_printable_or_space2; string = "{string_input}"'))
        print("filter + lru_cache", end=" : ")
        print(timeit.timeit('"".join(filter(is_printable_or_space2, string))', setup='from __main__ import is_printable_or_space2; string = "{string_input}"'))
```
</details>

<details>
<summary>results:</summary>

```python3
str_length=10
string_input = 'lhfbdxehsp'
Default : 0.7018209969974123
list_comprehension : 1.131737707000866
filter : 1.0729886770059238
list_comprehension + lru_cache : 1.0313369020004757
filter + lru_cache : 0.7164969980003661


str_length=20
string_input = 'mkphyddkdcgamlagnnfc'
Default : 1.1179964559996733
list_comprehension : 2.0401504339970415
filter : 1.0827240510043339
list_comprehension + lru_cache : 1.0022917479946045
filter + lru_cache : 0.7318965660015238


str_length=30
string_input = 'xadiziosmmtikyfhfzjwajnzoqokjt'
Default : 1.5371166080003604
list_comprehension : 2.93600173300365
filter : 1.0762741040016408
list_comprehension + lru_cache : 1.0011640379962046
filter + lru_cache : 0.7323283850055304


str_length=40
string_input = 'xzxoerutdrhkajuygrjupxlhanxowquqvqcsekjm'
Default : 1.9620843250013422
list_comprehension : 3.8560372499996447
filter : 1.0737007110001286
list_comprehension + lru_cache : 1.045567373999802
filter + lru_cache : 0.7321876290006912


str_length=50
string_input = 'qgjjfbqmnzkeunbdbgrnelhknkgpeqtjebjaxtiezeeyuhyauf'
Default : 2.404170144996897
list_comprehension : 4.731210878002457
filter : 1.0743210869986797
list_comprehension + lru_cache : 1.0056718409978203
filter + lru_cache : 0.740982076000364


str_length=60
string_input = 'rtcswicjquynihmbsqiuekoxiqhmufjbhzwccuhoqxcctmhnditmgrealnyh'
Default : 2.8501481999992393
list_comprehension : 5.653754784994817
filter : 1.0691139120026492
list_comprehension + lru_cache : 0.9985161919976235
filter + lru_cache : 0.7300572289968841


str_length=70
string_input = 'mpmsucejddudbmtaapomcjikxzfxtudhxxaftkqeqmntyzokleficjwtpqqwiopykvefwl'
Default : 3.3053956139992806
list_comprehension : 6.483927376000793
filter : 1.1196107380019384
list_comprehension + lru_cache : 1.0150398520054296
filter + lru_cache : 0.741182186997321


str_length=80
string_input = 'hkhowwzbboxtahnawyqrgmrpyweqvflyjtoexaclfeutvwphcwszvldbuskogosxkdrzvljdoggfleps'
Default : 3.78356299099687
list_comprehension : 7.459206407998863
filter : 1.0849218490038766
list_comprehension + lru_cache : 1.0124916560016572
filter + lru_cache : 0.7354401509946911


str_length=90
string_input = 'bzjodtubhbdxoekucclgxnswumjjzqulwvmlocrhuswuerpkbdnmwlingrjbbsmuyzspwjtbyabahmhlikoxpkbnll'
Default : 4.231246595001721
list_comprehension : 8.398667920999287
filter : 1.0956604860039079
list_comprehension + lru_cache : 1.0179264440012048
filter + lru_cache : 0.7371930520021124
```
</details>

___
### II. pprofile in real functions
install pprofile
```python3
pip install pprofile
```

<details>
<summary>test_pprofile.py</summary>

```python3
from functools import lru_cache
from random import randint


def is_printable_or_space(character):
    return character.isprintable() or character.isspace()

@lru_cache(maxsize=1114111)
def is_printable_or_space2(character):
    return character.isprintable() or character.isspace()

@profile
def default(string):
    return "".join([c for c in string if c.isprintable() or c.isspace()])

@profile
def filter_(string):
    return "".join(filter(is_printable_or_space, string))

@profile
def filter_cache(string):
    return "".join(filter(is_printable_or_space2, string))

if __name__ == '__main__':
    for _ in range(10_000):
        for str_length in range(10, 160, 10):            
            string_input = ''.join(chr(randint(97, 122)) for _ in range(str_length))
            default(string_input)
            filter_(string_input)
            filter_cache(string_input)
```
</details>

start test
```python3
python kernprof -lv test_pprofile.py
```
<details>
<summary>results</summary>

results
```python3
Total time: 2.58195 s
File: test_pprofile.py
Function: default at line 12

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    12                                           @profile
    13                                           def default(string):
    14    150000    2581949.0     17.2    100.0      return "".join([c for c in string if c.isprintable() or c.isspace()])

Total time: 3.43193 s
File: test_pprofile.py
Function: filter_ at line 16

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    16                                           @profile
    17                                           def filter_(string):
    18    150000    3431929.0     22.9    100.0      return "".join(filter(is_printable_or_space, string))

Total time: 0.90112 s
File: test_pprofile.py
Function: filter_cache at line 20

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    20                                           @profile
    21                                           def filter_cache(string):
    22    150000     901120.0      6.0    100.0      return "".join(filter(is_printable_or_space2, string))

```
</details>

**Comment by deedy5** [comment]
The whole point is to use the cache. You can also use list_comprehension, but in this case with filter cache works more efficiently.

**Comment by deedy5** [comment]
## Evaluation tests
before

```python3
number of documents: 750
nothing
{'true positives': 0, 'false positives': 0, 'true negatives': 2250, 'false negatives': 2236, 'time': 0}
everything
{'true positives': 1955, 'false positives': 1755, 'true negatives': 495, 'false negatives': 281, 'time': 0}
precision: 0.527 recall: 0.874 accuracy: 0.546 f-score: 0.658
baseline
{'true positives': 1886, 'false positives': 610, 'true negatives': 1640, 'false negatives': 350, 'time': 2.4738705158233643}
precision: 0.756 recall: 0.843 accuracy: 0.786 f-score: 0.797
html2text
{'true positives': 1586, 'false positives': 1677, 'true negatives': 573, 'false negatives': 650, 'time': 21.862650632858276}
precision: 0.486 recall: 0.709 accuracy: 0.481 f-score: 0.577
time diff.: 8.84
html_text
{'true positives': 2142, 'false positives': 1906, 'true negatives': 344, 'false negatives': 94, 'time': 5.316218137741089}
precision: 0.529 recall: 0.958 accuracy: 0.554 f-score: 0.682
time diff.: 2.15
inscriptis
{'true positives': 2144, 'false positives': 1869, 'true negatives': 381, 'false negatives': 92, 'time': 9.206528902053833}
precision: 0.534 recall: 0.959 accuracy: 0.563 f-score: 0.686
time diff.: 3.72
justext
{'true positives': 1453, 'false positives': 227, 'true negatives': 2023, 'false negatives': 783, 'time': 14.84993314743042}
precision: 0.865 recall: 0.650 accuracy: 0.775 f-score: 0.742
time diff.: 6.00
goose
{'true positives': 1539, 'false positives': 109, 'true negatives': 2141, 'false negatives': 697, 'time': 67.57892274856567}
precision: 0.934 recall: 0.688 accuracy: 0.820 f-score: 0.792
time diff.: 27.32
newspaper
{'true positives': 1325, 'false positives': 156, 'true negatives': 2094, 'false negatives': 911, 'time': 34.57500505447388}
precision: 0.895 recall: 0.593 accuracy: 0.762 f-score: 0.713
time diff.: 13.98
boilerpipe
{'true positives': 1663, 'false positives': 381, 'true negatives': 1869, 'false negatives': 573, 'time': 12.197097778320312}
precision: 0.814 recall: 0.744 accuracy: 0.787 f-score: 0.777
time diff.: 4.93
newsplease
{'true positives': 1643, 'false positives': 186, 'true negatives': 2064, 'false negatives': 593, 'time': 368.65222239494324}
precision: 0.898 recall: 0.735 accuracy: 0.826 f-score: 0.808
time diff.: 149.02
readability
{'true positives': 1629, 'false positives': 200, 'true negatives': 2050, 'false negatives': 607, 'time': 16.980444192886353}
precision: 0.891 recall: 0.729 accuracy: 0.820 f-score: 0.801
time diff.: 6.86
readabilipy
{'true positives': 2111, 'false positives': 1730, 'true negatives': 520, 'false negatives': 125, 'time': 163.2005271911621}
precision: 0.550 recall: 0.944 accuracy: 0.586 f-score: 0.695
time diff.: 65.97
bs4
{'true positives': 2045, 'false positives': 1784, 'true negatives': 466, 'false negatives': 191, 'time': 15.74964690208435}
precision: 0.534 recall: 0.915 accuracy: 0.560 f-score: 0.674
time diff.: 6.37
trafilatura
{'true positives': 1990, 'false positives': 190, 'true negatives': 2060, 'false negatives': 246, 'time': 12.755467891693115}
precision: 0.913 recall: 0.890 accuracy: 0.903 f-score: 0.901
time diff.: 5.16
trafilatura + X
{'true positives': 2023, 'false positives': 190, 'true negatives': 2060, 'false negatives': 213, 'time': 19.4944908618927}
precision: 0.914 recall: 0.905 accuracy: 0.910 f-score: 0.909
time diff.: 7.88
trafilatura precision
{'true positives': 1954, 'false positives': 143, 'true negatives': 2107, 'false negatives': 282, 'time': 26.412869930267334}
time diff.: 10.68
precision: 0.932 recall: 0.874 accuracy: 0.905 f-score: 0.902
trafilatura recall
{'true positives': 1982, 'false positives': 210, 'true negatives': 2040, 'false negatives': 254, 'time': 405.16265416145325}
time diff.: 163.78
precision: 0.904 recall: 0.886 accuracy: 0.897 f-score: 0.895
```
after
```python3
number of documents: 750
nothing
{'true positives': 0, 'false positives': 0, 'true negatives': 2250, 'false negatives': 2236, 'time': 0}
everything
{'true positives': 1955, 'false positives': 1755, 'true negatives': 495, 'false negatives': 281, 'time': 0}
precision: 0.527 recall: 0.874 accuracy: 0.546 f-score: 0.658
baseline
{'true positives': 1886, 'false positives': 610, 'true negatives': 1640, 'false negatives': 350, 'time': 2.5302765369415283}
precision: 0.756 recall: 0.843 accuracy: 0.786 f-score: 0.797
html2text
{'true positives': 1586, 'false positives': 1677, 'true negatives': 573, 'false negatives': 650, 'time': 21.947329998016357}
precision: 0.486 recall: 0.709 accuracy: 0.481 f-score: 0.577
time diff.: 8.67
html_text
{'true positives': 2142, 'false positives': 1906, 'true negatives': 344, 'false negatives': 94, 'time': 5.366196155548096}
precision: 0.529 recall: 0.958 accuracy: 0.554 f-score: 0.682
time diff.: 2.12
inscriptis
{'true positives': 2144, 'false positives': 1869, 'true negatives': 381, 'false negatives': 92, 'time': 9.266188621520996}
precision: 0.534 recall: 0.959 accuracy: 0.563 f-score: 0.686
time diff.: 3.66
justext
{'true positives': 1453, 'false positives': 227, 'true negatives': 2023, 'false negatives': 783, 'time': 15.045228719711304}
precision: 0.865 recall: 0.650 accuracy: 0.775 f-score: 0.742
time diff.: 5.95
goose
{'true positives': 1542, 'false positives': 109, 'true negatives': 2141, 'false negatives': 694, 'time': 68.28220057487488}
precision: 0.934 recall: 0.690 accuracy: 0.821 f-score: 0.793
time diff.: 26.99
newspaper
{'true positives': 1325, 'false positives': 156, 'true negatives': 2094, 'false negatives': 911, 'time': 34.89472413063049}
precision: 0.895 recall: 0.593 accuracy: 0.762 f-score: 0.713
time diff.: 13.79
boilerpipe
{'true positives': 1663, 'false positives': 381, 'true negatives': 1869, 'false negatives': 573, 'time': 12.068727493286133}
precision: 0.814 recall: 0.744 accuracy: 0.787 f-score: 0.777
time diff.: 4.77
newsplease
{'true positives': 1643, 'false positives': 186, 'true negatives': 2064, 'false negatives': 593, 'time': 435.4482901096344}
precision: 0.898 recall: 0.735 accuracy: 0.826 f-score: 0.808
time diff.: 172.10
readability
{'true positives': 1629, 'false positives': 200, 'true negatives': 2050, 'false negatives': 607, 'time': 17.30088520050049}
precision: 0.891 recall: 0.729 accuracy: 0.820 f-score: 0.801
time diff.: 6.84
readabilipy
{'true positives': 2111, 'false positives': 1730, 'true negatives': 520, 'false negatives': 125, 'time': 163.17165112495422}
precision: 0.550 recall: 0.944 accuracy: 0.586 f-score: 0.695
time diff.: 64.49
bs4
{'true positives': 2045, 'false positives': 1784, 'true negatives': 466, 'false negatives': 191, 'time': 16.481001377105713}
precision: 0.534 recall: 0.915 accuracy: 0.560 f-score: 0.674
time diff.: 6.51
trafilatura
{'true positives': 1990, 'false positives': 190, 'true negatives': 2060, 'false negatives': 246, 'time': 12.626954317092896}
precision: 0.913 recall: 0.890 accuracy: 0.903 f-score: 0.901
time diff.: 4.99
trafilatura + X
{'true positives': 2023, 'false positives': 190, 'true negatives': 2060, 'false negatives': 213, 'time': 19.576639652252197}
precision: 0.914 recall: 0.905 accuracy: 0.910 f-score: 0.909
time diff.: 7.74
trafilatura precision
{'true positives': 1954, 'false positives': 143, 'true negatives': 2107, 'false negatives': 282, 'time': 26.51164436340332}
time diff.: 10.48
precision: 0.932 recall: 0.874 accuracy: 0.905 f-score: 0.902
trafilatura recall
{'true positives': 1982, 'false positives': 210, 'true negatives': 2040, 'false negatives': 254, 'time': 405.04438757896423}
time diff.: 160.08
precision: 0.904 recall: 0.886 accuracy: 0.897 f-score: 0.895

```

**Comment by adbar** [comment]
Hi @deedy5, thanks for the additional info. I chose to use `map()` as I believe it is slightly faster.

Now the PR looks good to me, does that work for you?

**Comment by deedy5** [comment]
python 3.10.6
<details>
<summary>test.py</summary>

```python3
from functools import lru_cache
from random import randint


def is_printable_or_space(character):
    return character.isprintable() or character.isspace()

@lru_cache(maxsize=1114111)
def is_printable_or_space2(character):
    return character.isprintable() or character.isspace()

def return_printables_and_spaces(char):
    'Return a character if it belongs to certain classes'
    if char.isprintable() or char.isspace():
        return char
    return ''

@lru_cache(maxsize=1114111)  # sys.maxunicode = 1114111
def return_printables_and_spaces2(char):
    'Return a character if it belongs to certain classes'
    if char.isprintable() or char.isspace():
        return char
    return ''


if __name__ == '__main__':
    import timeit

    for str_length in [10, 50, 100, 150, 200]:
        print(f"\n\n{str_length=}")
        string_input = ''.join(chr(randint(97, 122)) for _ in range(str_length))
        print(f"{string_input = }")                               
        
        print("Default", end=" : ")
        print(timeit.timeit('"".join([c for c in string if c.isprintable() or c.isspace()])', setup=f'string = "{string_input}"'))
        print("filter + lambda", end=" : ")
        print(timeit.timeit('"".join(filter(lambda x: x.isprintable() or x.isspace(), string))', setup='string = "{string_input}"'))

        # no cache
        print("list_comprehension", end=" : ")
        print(timeit.timeit('"".join([c for c in string if is_printable_or_space(c)])', setup=f'from __main__ import is_printable_or_space; string = "{string_input}"'))
        print("filter", end=" : ")
        print(timeit.timeit('"".join(filter(is_printable_or_space, string))', setup='from __main__ import is_printable_or_space; string = "{string_input}"'))
        print("map", end=" : ")
        print(timeit.timeit('"".join(map(return_printables_and_spaces, string))', setup='from __main__ import return_printables_and_spaces; string = "{string_input}"'))        

        # cache
        print("list_comprehension + lru_cache", end=" : ")
        print(timeit.timeit('"".join([c for c in string if is_printable_or_space2(c)])', setup='from __main__ import is_printable_or_space2; string = "{string_input}"'))
        print("filter + lru_cache", end=" : ")
        print(timeit.timeit('"".join(filter(is_printable_or_space2, string))', setup='from __main__ import is_printable_or_space2; string = "{string_input}"'))
        print("map + lru_cache", end=" : ")
        print(timeit.timeit('"".join(map(return_printables_and_spaces2, string))', setup='from __main__ import return_printables_and_spaces2; string = "{string_input}"'))
```
</details>


<details>
<summary>results</summary>

```python3
str_length=10
string_input = 'lgpjaqwnhi'
Default : 0.703184798010625
filter + lambda : 1.119715445995098
list_comprehension : 1.132449254990206
filter : 1.080723193997983
map : 1.1246072719950462
list_comprehension + lru_cache : 0.9879924459964968
filter + lru_cache : 0.6971439729968552
map + lru_cache : 0.7426730659935856


str_length=50
string_input = 'fzsqsubfqfuhegdcnuybylizxofmwzitckhtjeauacuccanbye'
Default : 2.3598058039933676
filter + lambda : 1.1408991679927567
list_comprehension : 4.768937064000056
filter : 1.1085517299943604
map : 1.1306546069972683
list_comprehension + lru_cache : 1.0032081410026876
filter + lru_cache : 0.718972078000661
map + lru_cache : 0.746627679996891


str_length=100
string_input = 'dytniyfeozplfxfsdjizblkqtqappewreukbnrvwpjzrjbkvmgaoexzupkslrkqpviqlpiwnjtbkqljbiwofnfxxzdomalbfplre'
Default : 4.6583130749932025
filter + lambda : 1.119028054003138
list_comprehension : 9.399434025006485
filter : 1.0869811790034873
map : 1.145697978005046
list_comprehension + lru_cache : 1.0105660300032469
filter + lru_cache : 0.7110722250072286
map + lru_cache : 0.7627762490010355


str_length=150
string_input = 'gysdkwyevjamifsczlzprweiglhitebgbwnxjdcoofxbwzyntecyuprjkanaxdpmslbrqtvtecaxxqorlvfftzkjvnkmebjupxgbsrdpragnltdwvjhecyjcbzkmfqxtumpyudtjlhgkltqfdlfwid'
Default : 6.824055849996512
filter + lambda : 1.1281094799924176
list_comprehension : 14.258322855996084
filter : 1.1331063660036307
map : 1.208905796011095
list_comprehension + lru_cache : 1.0039256079908228
filter + lru_cache : 0.717826057007187
map + lru_cache : 0.7552197610057192


str_length=200
string_input = 'msunaywxktqqibsycfukceebyxjhseqorctamkuqdlsbmojsccplrvqxikjjgeshrlmwpbdcnzddyrycdtqbmvwudeecbpdxxzpsngshhogsjbuouafiptvupwwoxifbuqwjcjsdwndsdraxhleulclfbprcfdgrewzvpimswfmpgfixqvqrhonoyxirmrvmfotmdfej'
Default : 9.028333996000583
filter + lambda : 1.2428636560071027
list_comprehension : 18.54100680000556
filter : 1.0846985379903344
map : 1.1400741649995325
list_comprehension + lru_cache : 1.0097328819974791
filter + lru_cache : 0.7192968049930641
map + lru_cache : 0.749044459007564
```
</details>

___
summary:
still, filter() is a bit faster than map(). But I agree with map() as well.

**Comment by deedy5** [comment]
Tried several options that take into account the length of the input string, but alas, the results are worse. 
You can merge the branch.

**Comment by adbar** [comment]
Thanks for the additional benchmarks! On my computer (Python 3.8) `map()` is about 10% faster than `filter()`, so I'll use it for now.

**Pull request merged**
