### PR TITLE
added possibility to prune xPaths

### PR DESCRIPTION
**Pull request by HeLehm**
Same as I did in #259 .

Also: I added a simple test.

### CODE REVIEW

**Comment by adbar** [comment]
@HeLehm Thanks, the PR looks good, I'll hopefully merge it soon.

**Comment by HeLehm** [comment]
Hi @adbar, any updates on this? Can I do something to help?

**Comment by adbar** [comment]
Hi @HeLehm, I'll be afk for a little while but I'll merge your PR in October at the latest. In the meantime, could you please add the following tests? Not strictly speaking a coverage problem, rather a logical way to cover everything:

- You only test for `str` for `prune_xpath`, please also test with a list
- In your test the whole document is stripped, just add a test to make sure the right amount of text is removed

The two items can be combined.

**Comment by adbar** [comment]
Thanks! I don't quite understand why the coverage changes should be an issue and I plan to merge the PR as it is.

**Pull request merged**
