### PR TITLE
Extend test coverage for json_metadata functions, added fallback to author name when name is a string on article type

### PR DESCRIPTION
**Pull request by felipehertzer**
Hey @adbar,

I'm sending more tests to json metadata functions.

Thanks.

#195

### CODE REVIEW

**Comment by adbar** [comment]
Thanks @felipehertzer! I don't understand the coverage diff report, everything looks fine.

Did you mark the PR as draft? Are you still working on it?

**Comment by adbar** [comment]
I just merged it since everything looked OK.

**Comment by felipehertzer** [comment]
Hi @adbar,

I was checking the read json function https://github.com/felipehertzer/trafilatura/blob/fdab3df410f5cb4946f404ae305c41844a1b740e/trafilatura/metadata.py#L104

The regex is to minify the json but it is removing the ```\"``` when a value contains double quoutes ```"this is \"test2\" a test"```. Some tests are falling into except. But I could find a better way to minify and avoid to remove the escapes.

The coverage problem is that we need to test the json reading correctly and the json with problem.

**Comment by adbar** [comment]
Hi @felipehertzer, thanks for the info, feel free to make another PR if you make any progress!

**Pull request merged**
