### PR TITLE
Fixed unwanted content in some websites

### PR DESCRIPTION
**Pull request by felipehertzer**
Hey @adbar,

I did a check in the majors Australian websites and I added some classes and ids to the xpaths.py to avoid get unwanted content.

Canberra Times: (It was getting the newsletter box)
https://urlis.net/jw9sm5d2

The Australian (It was getting the related stories and most popular stories)
https://urlis.net/69cnu4ze

Courier Mail (It was getting an Amp box in the bottom)
https://urlis.net/qeuknv7n

Daily Mail (It was getting an 'exclusive' box and the comments)
https://urlis.net/z6gmds29

AFR (It was getting the author description in the bottom of the article)
https://urlis.net/ms64hmi5

ABC (It was getting a form in the bottom)
https://urlis.net/2yakvo39

The independent (it was showing comments)
https://urlis.net/rx3wq49x

Onya Magazine (It was getting the siderbar content instead of body)
https://urlis.net/m5mdzetf

Thank you.

### CODE REVIEW

**Comment by felipehertzer** [comment]
Hey @adbar, I just updated to include the class '-article'

**Comment by adbar** [comment]
Thanks for testing it, should I process the PR as it is now then?

There is still an odd error in certain tests but it should be OK.

**Comment by felipehertzer** [comment]
Yes you can proceed with this one, I think the tests started failing when I did the rebase.

**Comment by adbar** [comment]
I don't understand the bug on two test series, it doesn't make sense. I'll just wait a bit a restart the tests, maybe the problem will be solved or propagated to all versions by then.

**Comment by adbar** [comment]
@felipehertzer The problem is solved, can I merge the PR?

**Comment by felipehertzer** [comment]
@adbar Sure, all good for me.

**Comment by adbar** [comment]
I just removed an expression due to accuracy concerns, maybe "-comments" is just too broad. The rest work fine and even add a bit of precision on my benchmark, thanks!

**Pull request merged**
