### PR TITLE
feat: use proxy to extract data

### PR DESCRIPTION
**Pull request by andremacola**
This PR implements https://github.com/adbar/trafilatura/issues/330 and solves the issue https://github.com/adbar/trafilatura/issues/210

I have updated the downloads_tests.py file to reflect these changes, although I have not included a proxy test at this time. It maybe possible to read a private proxy variable in .env/settings.cfg for tests.

I can confirm that the HTTP/HTTPS SSL proxies are working correctly.

In order to use Socks4/5 proxies with urllib3, it is necessary to install the urllib3[socks] package using the command `python -m pip install urllib3[socks]` as described here: https://urllib3.readthedocs.io/en/stable/advanced-usage.html#socks-proxies. I did not have access to a Socks proxy for testing, I was unable to include this feature in the current pull request.

Finally, the trafilatura.fetch_url() function now includes a new parameter use_proxy, which can be used to specify a proxy in the format https://proxy_user:proxy_pass@proxy_host:proxy_port.

### CODE REVIEW

**Comment by adbar** [comment]
Hi @andremacola, thanks but this is a substantial change, it would be better if you could find a way to test for proxy behavior. As it is you've tested it separately but you added untested lines of code. There may be a way to mock the proxy in unit tests.

**Comment by andremacola** [comment]
@adbar I'll try to find some solution for tests. I admit that my knowledge in the area of proxy testing is limited.

Here are some thoughts:

1. We could create a docker container to simulate a proxy server (too much work to do)
2. Use a public proxies api just for tests (but this is not reliable)
3. Maybe find something in python to "fake a proxy"

**Comment by adbar** [comment]
I agree that solution 3 would be best, the proxies don't need to be real. Solution 2 otherwise, but right now there is a problem with `httpbin.org` which I use for other tests so yes, these APIs are not always reliable.

**Comment by adbar** [comment]
@andremacola Any news on the PR?

**Comment by andremacola** [comment]
> @andremacola Any news on the PR?

Sorry @adbar, right now I'm using this PR in my own project but currently my main job is taking up a lot of my time. I don't have any updates regarding the tests for this.

**Comment by adbar** [comment]
@andremacola Since we're not making progress right now I would close the PR, you can always re-open it later, does that work for you?

**Pull request closed without merging**
